/**
 * Habits Store
 * Zustand store for managing habits state
 * Generated by API generator
 */

import { create } from 'zustand';
import { habitsService } from '@/services/habits';
import type { Habit, CreateHabitInput, UpdateHabitInput } from '@/types/habits';

interface HabitsStore {
  // State
  items: Habit[];
  loading: boolean;
  error: string | null;

  // Actions
  fetchAll: () => Promise<void>;
  addItem: (data: CreateHabitInput | FormData) => Promise<Habit>;
  updateItem: (id: number, data: UpdateHabitInput | FormData) => Promise<Habit>;
  removeItem: (id: number) => Promise<void>;
  checkIn: (id: number, date?: string) => Promise<Habit>;
  reset: () => void;
}

export const useHabitsStore = create<HabitsStore>((set) => ({
  items: [],
  loading: false,
  error: null,

  fetchAll: async () => {
    set({ loading: true, error: null });
    try {
      const items = await habitsService.getAll();
      set({ items, loading: false });
    } catch (error: any) {
      console.error('Failed to fetch habits:', error);
      set({ error: error.message || 'Failed to load habits', loading: false });
    }
  },

  addItem: async (data: CreateHabitInput | FormData) => {
    try {
      const newItem = await habitsService.create(data);
      set((state) => ({
        items: [newItem, ...state.items]
      }));
      return newItem;
    } catch (error: any) {
      console.error('Failed to create habit:', error);
      set({ error: error.message || 'Failed to create habit' });
      throw error;
    }
  },

  updateItem: async (id: number, data: UpdateHabitInput | FormData) => {
    try {
      const updatedItem = await habitsService.update(id, data);
      set((state) => ({
        items: state.items.map(item =>
          item.id === id ? updatedItem : item
        )
      }));
      return updatedItem;
    } catch (error: any) {
      console.error('Failed to update habit:', error);
      set({ error: error.message || 'Failed to update habit' });
      throw error;
    }
  },

  removeItem: async (id: number) => {
    // Optimistic update
    set((state) => ({
      items: state.items.filter(item => item.id !== id)
    }));

    try {
      await habitsService.delete(id);
    } catch (error: any) {
      console.error('Failed to delete habit:', error);
      // Reload on error to restore deleted item
      try {
        const items = await habitsService.getAll();
        set({ items, error: error.message || 'Failed to delete habit' });
      } catch (reloadError) {
        set({ error: 'Failed to delete and reload habits' });
      }
      throw error;
    }
  },

  checkIn: async (id: number, date?: string) => {
    try {
      const updatedItem = await habitsService.checkIn(id, date);
      set((state) => ({
        items: state.items.map(item =>
          item.id === id ? updatedItem : item
        )
      }));
      return updatedItem;
    } catch (error: any) {
      console.error('Failed to check in habit:', error);
      set({ error: error.message || 'Failed to check in habit' });
      throw error;
    }
  },

  reset: () => set({ items: [], loading: false, error: null }),
}));
