/**
 * Habits API Service
 * Generated by API generator
 */

import { api } from './api';
import type { Habit, HabitResponse, HabitsResponse, CreateHabitInput, UpdateHabitInput } from '../types/habits';
import { API_BASE_URL } from '../config/api';

class HabitsService {
  /**
   * Get all habits
   */
  async getAll(): Promise<HabitsResponse> {
    return api.get<HabitsResponse>(`${API_BASE_URL}/api/v1/habits`);
  }

  /**
   * Get a single habit by ID
   */
  async getById(id: number): Promise<HabitResponse> {
    return api.get<HabitResponse>(`${API_BASE_URL}/api/v1/habits/${id}`);
  }

  /**
   * Create a new habit
   * Supports both JSON and FormData (for file uploads)
   */
  async create(data: CreateHabitInput | FormData): Promise<HabitResponse> {
    return api.post<HabitResponse>(`${API_BASE_URL}/api/v1/habits`, data);
  }

  /**
   * Update an existing habit
   * Supports both JSON and FormData (for file uploads)
   */
  async update(id: number, data: UpdateHabitInput | FormData): Promise<HabitResponse> {
    return api.put<HabitResponse>(`${API_BASE_URL}/api/v1/habits/${id}`, data);
  }

  /**
   * Delete a habit
   */
  async delete(id: number): Promise<void> {
    return api.delete<void>(`${API_BASE_URL}/api/v1/habits/${id}`);
  }

  /**
   * Check in a habit (mark as completed)
   * @param id - Habit ID
   * @param date - Optional date (defaults to today)
   */
  async checkIn(id: number, date?: string): Promise<HabitResponse> {
    const payload = date ? { date } : {};
    return api.post<HabitResponse>(`${API_BASE_URL}/api/v1/habits/${id}/check_in`, payload);
  }
}

export const habitsService = new HabitsService();
